:feelpp: Feel++
:cpp: C++
:project: feelpp-project 

= {feelpp} Project Template
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>
v2: 

image:https://github.com/feelpp/feelpp-project/workflows/CI/badge.svg[CI]

This repository provides a basic starting point for a {feelpp} application including:

- [x] {feelpp} applications in {cpp} to use {feelpp} and {feelpp} toolboxes in `src`
- [x] documentation using asciidoc and antora
- [x] python {feelpp} notebooks that can be downloaded from the documentation
- [x] continuous integration including tests for the {cpp} applications
- [x] docker image generation for the project

The documentation for feelpp-project is available at link:https://feelpp.github.io/feelpp-project[here] and you can build on it for your project by enabling the link:https://docs.github.com/en/pages[github pages] for your repository.

== Renaming the project

By default the project is named the project, you need to the following script and ansewer the questions:

 $ bash rename.sh 

== Release process

- [x] update the version in CMakeLists.txt
- [x] update the version in docs/antora.yml
- [x] commit the changes with the message "Release vx.y.z". At this point the CI will generate the docker image and push it to docker hub