name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docker enable')"
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag feelpp/feelpp-project
        docker push feelpp/feelpp-project
