name: Docs CI

on: 
  push:
    branches: 
      - '**' # Push events on all branches
    paths:
      - 'docs/**'
      - 'package*.json'
      - 'site.yml'
      - 'generate-jupyter.sh'
      - 'netlify*'
      - '.github/workflows/docs.yml'
      - 'requirements.txt'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/init.yml'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10 including semver

jobs:

  docs:
    runs-on: ubuntu-22.04
    name: Build Antora Site
    if: "!contains(github.event.head_commit.message, 'docs skip')"
    steps:
    - uses: actions/checkout@v4
    - name: Install credentials
      run: echo https://$GITHUB_OAUTH:@github.com > $HOME/.git-credentials
      env:
        GITHUB_OAUTH: ${{ secrets.CR_PAT_WORKFLOW }}
    - name: Install NPM dependencies
      run: npm install
    - name: Install Python dependencies
      run: |
          python -m venv --system-site-packages .venv
          source .venv/bin/activate
          pip install -r requirements.txt        
    - name: Build Antora Site
      run: |
          source .venv/bin/activate
          npm run antora
    - name: Deploy
      if: ${{ github.ref_name == 'master' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
